// Generated by 'unplugin-auto-import'
export {}
declare global {
  const ElMessage: typeof import('element-plus/es')['ElMessage']
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    readonly ElMessage: UnwrapRef<typeof import('element-plus/es')['ElMessage']>
  }
}
